### ISSUE TITLE
Make HTML input the default mode, instead of WYSIWYG

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/accordion-html-generator-react#6]
Now that this is in use, we're finding that the HTML input is users much more than the wizzy input. Can we make HTML the default?

**Comment by danfox01** [comment]
@mxsnyder Another one for you if time allows.

**Comment by martypowell** [comment]
@danfox01 guessing this is a pretty quick one that i can handle.

**Comment by danfox01** [comment]
Doesn't matter to me who grabs it. I was just trying to throw some quick ones Mike's way.

**Comment by martypowell** [comment]
@danfox01 these changes have been pushed to prod, and are confirmed
